DWAPlannerROS:
  max_vel_x: 0.22
  min_vel_x: 0.0
  max_vel_theta: 2.75
  min_vel_theta: 1.37

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  vx_samples: 20
  vtheta_samples: 40

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
